import { Router } from 'express';
import authRoutes from './auth.routes';
import studentAuthRoutes from './studentAuth.routes';
import homeworkRoutes from './homework.routes';
import studentRoutes from './student.routes';
import feeRoutes from './fee.routes';
import salaryRoutes from './salary.routes';
import schoolRoutes from './school.routes';
import masterRoutes from './master.routes';
import userRoutes from './user.routes';
import staffRoutes from './staff.routes';
import examRoutes from './exam.routes';
import transportRoutes from './transport.routes';
import uploadRoutes from './upload.routes';
import salaryStructureRoutes from './salaryStructure.routes';
import otherPaymentRoutes from './otherPayment.routes';
import userNotificationRoutes from './userNotification.routes';
import sessionRoutes from './session.routes';
import classRoutes from './class.routes';
import timetableRoutes from './timetable.routes';
import aiRoutes from './ai.routes';
import paymentRoutes from './payment.routes';
import notificationRoutes from './notification.routes';
import announcementRoutes from './announcement.routes';
import supportRoutes from './support.routes';
import attendanceRoutes from './attendance.routes';
import staffAttendanceRoutes from './staffAttendance.routes';
import studentNotificationRoutes from './studentNotification.routes';
import transportAttendanceRoutes from './transportAttendance.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/auth/student', studentAuthRoutes);
router.use('/homework', homeworkRoutes);
router.use('/master', masterRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentRoutes);
router.use('/fees', feeRoutes);
router.use('/salaries', salaryRoutes);
router.use('/salary-structure', salaryStructureRoutes);
router.use('/salary-other-payments', otherPaymentRoutes);
router.use('/user-notifications', userNotificationRoutes);
router.use('/users', userRoutes);
router.use('/staff', staffRoutes);
router.use('/exams', examRoutes);
router.use('/transport', transportRoutes);
router.use('/upload', uploadRoutes);
router.use('/sessions', sessionRoutes);
router.use('/classes', classRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/staff-attendance', staffAttendanceRoutes);
router.use('/transport-attendance', transportAttendanceRoutes);
router.use('/student-notifications', studentNotificationRoutes);
router.use('/timetable', timetableRoutes);

router.use('/ai', aiRoutes);
router.use('/payments', paymentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/announcements', announcementRoutes);
router.use('/support', supportRoutes);

export default router;
